# Task 1: Data Preparation

In this section, we load the House Price dataset, identify missing values in both train and test sets, and then clean the data by imputing those missing values using appropriate strategies (median for numerical, mode for categorical, and "None" where absence is meaningful). Finally, we encode categorical features and save the cleaned file.

### Importing Libraries

In [ ]:
import pandas as pd

pd.set_option('display.max_columns', None)
# this below code will ignore any warnings appear after running the cell.
import warnings
warnings.filterwarnings('ignore')

### Loading the Dataset

We read both train and test CSV files from Kaggle.

In [ ]:
train_data = pd.read_csv('/content/house_price_classification.csv')

Quick look at the first few rows of training data to understand the structure.

In [ ]:
train_data.head()

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,2
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,1
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,2
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,1
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,2

In [ ]:
train_data.shape

(1460, 83)

In [ ]:
train_data.drop(['SalePrice','PriceCategory'],axis=1)

,Unnamed: 0,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2003,2003,Gable,CompShg,VinylSd,VinylSd,BrkFace,196.0,Gd,TA,PConc,Gd,TA,No,GLQ,706,Unf,0,150,856,GasA,Ex,Y,SBrkr,856,854,0,1710,1,0,2,1,3,1,Gd,8,Typ,0,NaN,Attchd,2003.0,RFn,2,548,TA,TA,Y,0,61,0,0,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,Norm,1Fam,1Story,6,8,1976,1976,Gable,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,Gd,TA,Gd,ALQ,978,Unf,0,284,1262,GasA,Ex,Y,SBrkr,1262,0,0,1262,0,1,2,0,3,1,TA,6,Typ,1,TA,Attchd,1976.0,RFn,2,460,TA,TA,Y,298,0,0,0,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,Norm,1Fam,2Story,7,5,2001,2002,Gable,CompShg,VinylSd,VinylSd,BrkFace,162.0,Gd,TA,PConc,Gd,TA,Mn,GLQ,486,Unf,0,434,920,GasA,Ex,Y,SBrkr,920,866,0,1786,1,0,2,1,3,1,Gd,6,Typ,1,TA,Attchd,2001.0,RFn,2,608,TA,TA,Y,0,42,0,0,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,5,1915,1970,Gable,CompShg,Wd Sdng,Wd Shng,NaN,0.0,TA,TA,BrkTil,TA,Gd,No,ALQ,216,Unf,0,540,756,GasA,Gd,Y,SBrkr,961,756,0,1717,1,0,1,0,3,1,Gd,7,Typ,1,Gd,Detchd,1998.0,Unf,3,642,TA,TA,Y,0,35,272,0,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,Norm,1Fam,2Story,8,5,2000,2000,Gable,CompShg,VinylSd,VinylSd,BrkFace,350.0,Gd,TA,PConc,Gd,TA,Av,GLQ,655,Unf,0,490,1145,GasA,Ex,Y,SBrkr,1145,1053,0,2198,1,0,2,1,4,1,Gd,9,Typ,1,TA,Attchd,2000.0,RFn,3,836,TA,TA,Y,192,84,0,0,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Gilbert,Norm,Norm,1Fam,2Story,6,5,1999,2000,Gable,CompShg,VinylSd,VinylSd,NaN,0.0,TA,TA,PConc,Gd,TA,No,Unf,0,Unf,0,953,953,GasA,Ex,Y,SBrkr,953,694,0,1647,0,0,2,1,3,1,TA,7,Typ,1,TA,Attchd,1999.0,RFn,2,460,TA,TA,Y,0,40,0,0,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
1456,1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NWAmes,Norm,Norm,1Fam,1Story,6,6,1978,1988,Gable,CompShg,Plywood,Plywood,Stone,119.0,TA,TA,CBlock,Gd,TA,No,ALQ,790,Rec,163,589,1542,GasA,TA,Y,SBrkr,2073,0,0,2073,1,0,2,0,3,1,TA,7,Min1,2,TA,Attchd,1978.0,Unf,2,500,TA,TA,Y,349,0,0,0,0,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal
1457,1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Crawfor,Norm,Norm,1Fam,2Story,7,9,1941,2006,Gable,CompShg,CemntBd,CmentBd,NaN,0.0,Ex,Gd,Stone,TA,Gd,No,GLQ,275,Unf,0,877,1152,GasA,Ex,Y,SBrkr,1188,1152,0,2340,0,0,2,0,4,1,Gd,9,Typ,2,Gd,Attchd,1941.0,RFn,1,252,TA,TA,Y,0,60,0,0,0,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal
1458,1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,NAmes,Norm,Norm,1Fam,1Story,5,6,1950,1996,Hip,CompShg,MetalSd,MetalSd,NaN,0.0,TA,TA,CBlock,TA,TA,Mn,GLQ,49,Rec,1029,0,1078,GasA,Gd,Y,FuseA,1078,0,0,1078,1,0,1,0,2,1,Gd,5,Typ,0,NaN,Attchd,1950.0,Unf,1,240,TA,TA,Y,366,0,112,0,0,0,NaN,NaN,NaN,0,4,2010,WD,Normal
1459,1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,Inside,Gtl,Edwards,Norm,Norm,1Fam,1Story,5,6,1965,1965,Gable,CompShg,HdBoard,HdBoard,NaN,0.0,Gd,TA,CBlock,TA,TA,No,BLQ,830,LwQ,290,136,1256,GasA,Gd,Y,SBrkr,1256,0,0,1256,1,0,1,1,3,1,TA,6,Typ,0,NaN,Attchd,1965.0,Fin,1,276,TA,TA,Y,736,68,0,0,0,0,NaN,NaN,NaN,0,6,2008,WD,Normal

### Checking for Missing Values

Before cleaning anything, let's see which columns have missing values and how many — separately for train and test.

In [ ]:
# This line of code prints all columns where there are missing values in train data set.
train_cols = train_data.columns
missing_train_cols = []
missing_train_val = []
for col in train_cols:
    if train_data[col].isnull().sum() > 0:
        missing_train_cols.append(col)
        missing_train_val.append(train_data[col].isnull().sum())
        print(f"column {col} have {train_data[col].isnull().sum()} missing values.")
# print(missing_train_cols,missing_train_val)

column LotFrontage have 259 missing values.
column Alley have 1369 missing values.
column MasVnrType have 872 missing values.
column MasVnrArea have 8 missing values.
column BsmtQual have 37 missing values.
column BsmtCond have 37 missing values.
column BsmtExposure have 38 missing values.
column BsmtFinType1 have 37 missing values.
column BsmtFinType2 have 38 missing values.
column Electrical have 1 missing values.
column FireplaceQu have 690 missing values.
column GarageType have 81 missing values.
column GarageYrBlt have 81 missing values.
column GarageFinish have 81 missing values.
column GarageQual have 81 missing values.
column GarageCond have 81 missing values.
column PoolQC have 1453 missing values.
column Fence have 1179 missing values.
column MiscFeature have 1406 missing values.

In [ ]:
# Since PoolQC, MiscFeature have large missing values so dropped it
train_data.drop(['PoolQC','MiscFeature'],axis=1,inplace=True)

# Imputation Of Missing Values (Most Imp.)

#### Imputing Train Data

- Numerical columns like `LotFrontage`, `MasVnrArea`, `GarageYrBlt` are filled with **median** since median is robust to outliers.
- `Electrical` had just a couple of missing rows so we used **mode** (most frequent value).
- For basement and garage related columns, missing values actually mean the house doesn't have that feature, so we fill with `"None"`.
- Same logic for columns like `Alley`, `PoolQC`, `Fence` etc. — high missing % because most houses simply don't have them.

In [ ]:
# Here I have filled numerical values with median
train_data['LotFrontage'].fillna(train_data['LotFrontage'].median(), inplace=True)
train_data['MasVnrArea'].fillna(train_data['MasVnrArea'].median(), inplace=True)
train_data['GarageYrBlt'].fillna(train_data['GarageYrBlt'].median(), inplace=True)

# Here I have filled categorical values with mode (there were few missing values)
train_data['Electrical'].fillna(train_data['Electrical'].mode()[0], inplace=True)

# Here I have filled categorical values with median
bsmt_cols = ['BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2']
for col in bsmt_cols:
    train_data[col].fillna('None', inplace=True)

# Filled Garage features having missing values with "None" that means "No Garage"
garage_cols = ['GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']
for col in garage_cols:
    train_data[col].fillna('None', inplace=True)

# columns having high missing values replaced with None as well.
high_missing_cols = ['Alley', 'FireplaceQu', 'Fence','PoolQC','MiscFeature']
for col in high_missing_cols:
    train_data[col].fillna('None', inplace=True)

# Special case
train_data['MasVnrType'].fillna('None', inplace=True)

# Check if any missing values remain
print(train_data.isnull().sum().sort_values(ascending=False).head(10))

Unnamed: 0     0
Id             0
MSSubClass     0
MSZoning       0
LotFrontage    0
LotArea        0
Street         0
Alley          0
LotShape       0
LandContour    0
dtype: int64

# Next Steps
# 1) Apply One hot encoding/Label encoding on categorical columns Since ML models only takes numerical values as input.

### Label Encoding Categorical Columns

ML models need numerical input, so we convert all categorical (text) columns to numbers using `LabelEncoder`. We fit the encoder on training data and then apply the same mapping to test data. If test data has a category the encoder never saw during training, we replace it with the most frequent training category to avoid errors.

In [ ]:
from sklearn.preprocessing import LabelEncoder
import numpy as np

In [ ]:
categorical_cols = train_data.select_dtypes(include=['object']).columns

In [ ]:
categorical_cols

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'Fence', 'SaleType', 'SaleCondition'],
      dtype='object')

In [ ]:
label_encoders = {}

for col in categorical_cols:
    le = LabelEncoder()
    train_data[col] = le.fit_transform(train_data[col].astype(str))
    label_encoders[col] = le

### Final Check — Any Missing Values Left?

In [ ]:
train_data.isna().sum()

Unnamed: 0       0
Id               0
MSSubClass       0
MSZoning         0
LotFrontage      0
                ..
YrSold           0
SaleType         0
SaleCondition    0
SalePrice        0
PriceCategory    0
Length: 81, dtype: int64

### Saving the Cleaned Dataset

We save the fully cleaned and encoded training data as `train_cleaned.csv`.

In [ ]:
train_data.to_csv('/content/house_price_classification_cleaned.csv')

# Task 2
## Data Split

Here we split the cleaned training data into train/test pairs at three different ratios: **70:30**, **75:25**, and **80:20**. We use `random_state=42` so the splits are reproducible every time.

In [ ]:
from sklearn.model_selection import train_test_split

#### Separating Features (X) and Target (y)

We drop `Id` because it's just an identifier and `SalePrice` because that's what we want to predict.

In [ ]:
y = train_data['PriceCategory']
X = train_data.drop(['Id','PriceCategory'], axis = 1)

#### Performing the Three Splits

In [ ]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X, y, test_size=0.3,random_state=42)

In [ ]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X, y,test_size=0.25,random_state=42)

In [ ]:
X_train3, X_test3, y_train3, y_test3 = train_test_split(X, y,test_size=0.2,random_state=42)

#### Saving Training Files

We recombine X and y for each split and save them as separate CSVs.

In [ ]:
X_train_70 = pd.concat([X_train1,y_train1],axis=1)

In [ ]:
X_train_75 = pd.concat([X_train2,y_train2],axis=1)

In [ ]:
X_train_80 = pd.concat([X_train3,y_train3],axis=1)

In [ ]:
X_train_70.head()

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
135,135,20,3,80.0,10400,1,1,3,3,0,4,0,14,2,2,0,2,7,6,1970,1970,3,1,9,10,1,288.0,3,4,2,4,4,3,6,0,6,0,1304,1304,1,2,1,4,1682,0,0,1682,0,0,2,0,3,1,3,7,6,1,2,1,1970.0,3,2,530,5,5,2,98,0,0,0,0,0,2,0,5,2008,8,4,174000,1
1452,1452,180,4,35.0,3675,1,1,3,3,0,4,0,7,2,2,4,7,5,5,2005,2005,1,1,12,13,1,80.0,3,4,2,2,4,1,2,547,6,0,0,547,1,2,1,4,1072,0,0,1072,1,0,1,0,2,1,3,5,6,0,3,2,2005.0,0,2,525,5,5,2,0,28,0,0,0,0,4,0,5,2006,8,4,145000,1
762,762,60,1,72.0,8640,1,1,3,3,0,4,0,21,2,2,0,5,7,5,2009,2009,1,1,12,13,2,0.0,3,4,2,2,4,2,2,24,6,0,732,756,1,0,1,4,764,783,0,1547,0,0,2,1,3,1,2,7,6,0,3,1,2009.0,3,2,614,5,5,2,169,45,0,0,0,0,4,0,6,2010,2,4,215200,2
932,932,20,3,84.0,11670,1,1,0,3,0,0,0,21,8,2,0,2,9,5,2006,2006,3,1,12,7,3,302.0,0,4,2,0,1,3,6,0,6,0,1905,1905,1,0,1,4,1905,0,0,1905,0,0,2,0,3,1,0,8,6,1,2,1,2006.0,0,3,788,5,5,2,0,191,0,0,0,0,4,0,3,2007,8,4,320000,2
435,435,60,3,43.0,10667,1,1,1,3,0,1,0,5,4,2,0,5,7,6,1996,1996,1,1,12,13,2,0.0,2,4,2,2,4,0,2,385,0,344,70,799,1,0,1,4,827,834,0,1661,1,0,2,1,3,1,2,6,6,1,5,1,1996.0,2,2,550,5,5,2,158,61,0,0,0,0,4,0,4,2009,5,4,212000,2

In [ ]:
X_train_70.to_csv('/content/clean_train_70.csv')

In [ ]:
X_train_75.to_csv('/content/clean_train_75.csv')

In [ ]:
X_train_80.to_csv('/content/clean_train_80.csv')

#### Saving Testing Files

In [ ]:
X_test_30 = pd.concat([X_test1,y_test1],axis=1)

In [ ]:
X_test_25 = pd.concat([X_test2,y_test2],axis=1)

In [ ]:
X_test_20 = pd.concat([X_test3,y_test3],axis=1)

In [ ]:
X_test_30.to_csv('/content/clean_test_30.csv')

In [ ]:
X_test_25.to_csv('/content/clean_test_25.csv')

In [ ]:
X_test_20.to_csv('/content/clean_test_20.csv')

In [ ]:
X_test_30.head()

,Unnamed: 0,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,Condition2,BldgType,HouseStyle,OverallQual,OverallCond,YearBuilt,YearRemodAdd,RoofStyle,RoofMatl,Exterior1st,Exterior2nd,MasVnrType,MasVnrArea,ExterQual,ExterCond,Foundation,BsmtQual,BsmtCond,BsmtExposure,BsmtFinType1,BsmtFinSF1,BsmtFinType2,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,Heating,HeatingQC,CentralAir,Electrical,1stFlrSF,2ndFlrSF,LowQualFinSF,GrLivArea,BsmtFullBath,BsmtHalfBath,FullBath,HalfBath,BedroomAbvGr,KitchenAbvGr,KitchenQual,TotRmsAbvGrd,Functional,Fireplaces,FireplaceQu,GarageType,GarageYrBlt,GarageFinish,GarageCars,GarageArea,GarageQual,GarageCond,PavedDrive,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,Fence,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,PriceCategory
892,892,20,3,70.0,8414,1,1,3,3,0,4,0,19,2,2,0,2,6,8,1963,2003,3,1,6,6,2,0.0,3,4,1,4,4,3,2,663,6,0,396,1059,1,4,1,4,1068,0,0,1068,0,1,1,0,3,1,3,6,6,0,3,1,1963.0,2,1,264,5,5,2,192,0,0,0,0,0,2,0,2,2006,8,4,154500,1
1105,1105,60,3,98.0,12256,1,1,0,3,0,0,0,15,2,2,0,5,8,5,1994,1995,1,1,6,6,1,362.0,2,4,2,0,4,0,2,1032,6,0,431,1463,1,0,1,4,1500,1122,0,2622,1,0,2,1,3,1,2,9,6,2,5,1,1994.0,2,2,712,5,5,2,186,32,0,0,0,0,4,0,4,2010,8,4,325000,2
413,413,30,4,56.0,8960,1,0,3,3,0,4,0,17,0,2,0,2,5,6,1927,1950,1,1,14,15,2,0.0,3,4,1,4,4,3,6,0,6,0,1008,1008,1,2,1,0,1028,0,0,1028,0,0,1,0,2,1,3,5,6,1,2,5,1927.0,3,2,360,5,5,2,0,0,130,0,0,0,4,0,3,2010,8,4,115000,0
522,522,50,4,50.0,5000,1,1,3,3,0,0,0,3,1,2,0,0,6,7,1947,1950,1,1,5,5,2,0.0,3,2,1,4,4,3,0,399,6,0,605,1004,1,0,1,4,1004,660,0,1664,0,0,2,0,3,1,3,7,6,2,2,5,1950.0,3,2,420,5,5,2,0,24,36,0,0,0,4,0,10,2006,8,4,159000,1
1036,1036,20,3,89.0,12898,1,1,0,1,0,4,0,23,2,2,0,2,9,5,2007,2008,3,1,12,13,3,70.0,2,4,2,0,4,1,2,1022,6,0,598,1620,1,0,1,4,1620,0,0,1620,1,0,2,0,2,1,0,6,6,1,0,1,2008.0,0,3,912,5,5,2,228,0,0,0,0,0,4,0,9,2009,8,4,315500,2

## Part A: Decision Tree Algorithm

We will train a Decision Tree Classifier on the house price data using four different hyperparameter combinations:

| # | Criterion | max_depth |
|---|-----------|----------|
| 1 | entropy   | 4        |
| 2 | entropy   | 5        |
| 3 | gini      | 4        |
| 4 | gini      | 5        |

Since `SalePrice` is a continuous variable and entropy/gini are classification criteria, we first convert `SalePrice` into price categories (Low, Medium, High) based on percentile ranges. This way we can properly use a classifier here.

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report
import pandas as pd
import numpy as np

### Train-Test Split (70:30)

We'll use the 70:30 split for training and evaluating all four Decision Tree models.

In [ ]:
X_train = pd.read_csv('/content/clean_train_70.csv', index_col=0)
X_test = pd.read_csv('/content/clean_test_30.csv', index_col=0)

In [ ]:
X_train.shape

(1022, 80)

### Preparing Features and Target

In [ ]:
y_train = X_train['PriceCategory']
y_test = X_test['PriceCategory']

X_train = X_train.drop(['SalePrice', 'PriceCategory'], axis=1)
X_test = X_test.drop(['SalePrice', 'PriceCategory'], axis=1)

### Model 1 — Criterion: Entropy, max_depth: 4

In [ ]:
dt1 = DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=42)
dt1.fit(X_train, y_train)
y_pred1 = dt1.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, y_pred1):.4f}')

Accuracy: 0.7740

### Model 2 — Criterion: Entropy, max_depth: 5

In [ ]:
dt2 = DecisionTreeClassifier(criterion='entropy', max_depth=5, random_state=42)
dt2.fit(X_train, y_train)
y_pred2 = dt2.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, y_pred2):.4f}')

Accuracy: 0.7785

### Model 3 — Criterion: Gini, max_depth: 4

In [ ]:
dt3 = DecisionTreeClassifier(criterion='gini', max_depth=4, random_state=42)
dt3.fit(X_train, y_train)
y_pred3 = dt3.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, y_pred3):.4f}')

Accuracy: 0.7580

### Model 4 — Criterion: Gini, max_depth: 5

In [ ]:
dt4 = DecisionTreeClassifier(criterion='gini', max_depth=5, random_state=42)
dt4.fit(X_train, y_train)
y_pred4 = dt4.predict(X_test)

print(f'Accuracy: {accuracy_score(y_test, y_pred4):.4f}')

Accuracy: 0.7763

# Saving Models

In [ ]:
from joblib import dump

In [ ]:
# save model
filename = f'/content/DT_gini_4_70.joblib'
dump(dt1, filename)

['/content/DT_gini_4_70.joblib']

#just for Understanding

### Hyperparameter Tuning using GridSearchCV

Instead of manually trying each combination of criterion and max_depth like we did above, scikit-learn gives us a built-in way to do this automatically — `GridSearchCV`. It takes a dictionary of hyperparameters, tries every possible combination, evaluates each using cross-validation, and tells us which combination performed the best. Think of it as a smarter way of doing what we just did manually.

In [ ]:
from sklearn.model_selection import GridSearchCV

# defining the hyperparameters we want to try
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [4, 5]
}

# setting up grid search with 5-fold cross validation
dt = DecisionTreeClassifier(random_state=42)
grid_search = GridSearchCV(dt, param_grid, cv=10, scoring='accuracy')

# fitting on training data (using the 70:30 split)
grid_search.fit(X_train, y_train)

# results
print("All combinations tried:")
cv_results = pd.DataFrame(grid_search.cv_results_)[['param_criterion', 'param_max_depth', 'mean_test_score']]
cv_results.columns = ['Criterion', 'max_depth', 'Avg CV Accuracy']
print(cv_results.to_string(index=False))

print(f"\nBest Parameters: {grid_search.best_params_}")
print(f"Best CV Accuracy: {grid_search.best_score_:.4f}")
print(f"Test Accuracy: {grid_search.score(X_test, y_test):.4f}")

All combinations tried:
Criterion  max_depth  Avg CV Accuracy
     gini          4         0.741719
     gini          5         0.748563
  entropy          4         0.729973
  entropy          5         0.740720

Best Parameters: {'criterion': 'gini', 'max_depth': 5}
Best CV Accuracy: 0.7486
Test Accuracy: 0.7763